//
//    MainWorker.swift
//    RadioHermitage
//
//    Created by Artem Kovardin on 14.03.2020.
//    Copyright (c) 2020 Artem Kovardin. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

import UIKit
import AVFoundation

protocol MainServiceLogic {
    func play()
    func stop()
}

class MainService: MainServiceLogic {
    var player: AVPlayer = {
        let url = URL(string: "http://91.190.127.185:8000/live_test")
        let player = AVPlayer(url: url!)

        return player
    }()

    func play() {
        player.play()
    }

    func stop() {
        player.pause()
    }
}
